language: rust
rust:
  - stable
  - beta
  - 1.34.0  # The minimal Rust version we claim we need.
before_script:
  - rustup component add clippy
script:
  - cargo clippy -- -D warnings
  - cargo test --verbose

